include:
  - board: nrfmicro_13
    shield: rt-22_left
  - board: nrfmicro_13
    shield: rt-22_right
  - board: nrfmicro_13
    shield: rt-22-legacy_left
  - board: nrfmicro_13
    shield: rt-22-legacy_right
  - board: nrfmicro_13
    shield: chocofi_left
  - board: nrfmicro_13
    shield: chocofi_right
  - board: nrfmicro_13
    shield: settings_reset
  - board: nrfmicro_13
    shield: test-board
