include:
  - board: nrfmicro/nrf52840
    shield: rt-22_left
  - board: nrfmicro/nrf52840
    shield: rt-22_right
  - board: nice_nano
    shield: rt-22_left
  - board: nice_nano
    shield: rt-22_right
  - board: nrfmicro/nrf52833
    shield: tbk_mini_left
  - board: nrfmicro/nrf52833
    shield: tbk_mini_right
  - board: nrfmicro/nrf52840
    shield: settings_reset
  - board: nrfmicro/nrf52833
    shield: settings_reset
  - board: nrfmicro/nrf52840
    shield: test-board
  - board: nrfmicro/nrf52833
    shield: test-board 
